version: "3"

services:
  marketplace:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    ports:
      - "4040:4040"
    env_file:
      - .env
    depends_on:
      - postgres
      - pgadmin
    networks:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:

